/* Automatically generated by tree-sitter v0.25.2 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_RBRACE_RBRACE = 3,
  anon_sym_EQ = 4,
  anon_sym_COMMA = 5,
  anon_sym_ATcomponent_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_ATdump_LPAREN = 8,
  anon_sym_ATeach_LPAREN = 9,
  anon_sym_in = 10,
  anon_sym_ATelse = 11,
  anon_sym_ATend = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_literal_token1 = 14,
  anon_sym_SQUOTE = 15,
  aux_sym_string_literal_token2 = 16,
  anon_sym_DASH = 17,
  anon_sym_BANG = 18,
  anon_sym_STAR = 19,
  anon_sym_PERCENT = 20,
  anon_sym_SLASH = 21,
  anon_sym_PLUS = 22,
  sym_number_int = 23,
  anon_sym_true = 24,
  anon_sym_false = 25,
  sym_program = 26,
  sym__definition = 27,
  sym_brace_statement = 28,
  sym_statement = 29,
  sym_expression_statement = 30,
  sym_assign_statement = 31,
  sym_block_statement = 32,
  sym_argument_list = 33,
  sym_component_statement = 34,
  sym_dump_statement = 35,
  sym_each_statement = 36,
  sym_string_literal = 37,
  sym__expression = 38,
  sym_prefix_expression = 39,
  sym_prefix_minus = 40,
  sym_prefix_not = 41,
  sym_infix_expression = 42,
  sym_multiply = 43,
  sym_modulo = 44,
  sym_divide = 45,
  sym_minus = 46,
  sym_plus = 47,
  sym_boolean_literal = 48,
  aux_sym_program_repeat1 = 49,
  aux_sym_argument_list_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_ATcomponent_LPAREN] = "@component(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATdump_LPAREN] = "@dump(",
  [anon_sym_ATeach_LPAREN] = "@each(",
  [anon_sym_in] = "in",
  [anon_sym_ATelse] = "@else",
  [anon_sym_ATend] = "@end",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_STAR] = "*",
  [anon_sym_PERCENT] = "%",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [sym_number_int] = "number_int",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_program] = "program",
  [sym__definition] = "_definition",
  [sym_brace_statement] = "brace_statement",
  [sym_statement] = "statement",
  [sym_expression_statement] = "expression_statement",
  [sym_assign_statement] = "assign_statement",
  [sym_block_statement] = "block_statement",
  [sym_argument_list] = "argument_list",
  [sym_component_statement] = "component_statement",
  [sym_dump_statement] = "dump_statement",
  [sym_each_statement] = "each_statement",
  [sym_string_literal] = "string_literal",
  [sym__expression] = "_expression",
  [sym_prefix_expression] = "prefix_expression",
  [sym_prefix_minus] = "prefix_minus",
  [sym_prefix_not] = "prefix_not",
  [sym_infix_expression] = "infix_expression",
  [sym_multiply] = "multiply",
  [sym_modulo] = "modulo",
  [sym_divide] = "divide",
  [sym_minus] = "minus",
  [sym_plus] = "plus",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_ATcomponent_LPAREN] = anon_sym_ATcomponent_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATdump_LPAREN] = anon_sym_ATdump_LPAREN,
  [anon_sym_ATeach_LPAREN] = anon_sym_ATeach_LPAREN,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_ATelse] = anon_sym_ATelse,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_number_int] = sym_number_int,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_program] = sym_program,
  [sym__definition] = sym__definition,
  [sym_brace_statement] = sym_brace_statement,
  [sym_statement] = sym_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_assign_statement] = sym_assign_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_argument_list] = sym_argument_list,
  [sym_component_statement] = sym_component_statement,
  [sym_dump_statement] = sym_dump_statement,
  [sym_each_statement] = sym_each_statement,
  [sym_string_literal] = sym_string_literal,
  [sym__expression] = sym__expression,
  [sym_prefix_expression] = sym_prefix_expression,
  [sym_prefix_minus] = sym_prefix_minus,
  [sym_prefix_not] = sym_prefix_not,
  [sym_infix_expression] = sym_infix_expression,
  [sym_multiply] = sym_multiply,
  [sym_modulo] = sym_modulo,
  [sym_divide] = sym_divide,
  [sym_minus] = sym_minus,
  [sym_plus] = sym_plus,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcomponent_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdump_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATeach_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_number_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_brace_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_component_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_dump_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_each_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_not] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_multiply] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym_divide] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_array = 2,
  field_name = 3,
  field_value = 4,
  field_var = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_array] = "array",
  [field_name] = "name",
  [field_value] = "value",
  [field_var] = "var",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_value, 2},
  [3] =
    {field_array, 3},
    {field_var, 1},
  [5] =
    {field_alternative, 7},
    {field_array, 3},
    {field_var, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '!', 43,
        '"', 36,
        '%', 45,
        '\'', 39,
        ')', 30,
        '*', 44,
        '+', 47,
        ',', 28,
        '-', 42,
        '/', 46,
        '=', 27,
        '@', 5,
        '{', 22,
        '}', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(15);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(2);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(1);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 22:
      if (lookahead == '{') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == '}') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_ATcomponent_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_ATdump_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_ATeach_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_ATelse);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 37},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 40},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_ATcomponent_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATdump_LPAREN] = ACTIONS(1),
    [anon_sym_ATeach_LPAREN] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_ATelse] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_number_int] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(51),
    [sym__definition] = STATE(16),
    [sym_brace_statement] = STATE(16),
    [sym_component_statement] = STATE(16),
    [sym_dump_statement] = STATE(16),
    [sym_each_statement] = STATE(16),
    [aux_sym_program_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_ATcomponent_LPAREN] = ACTIONS(7),
    [anon_sym_ATdump_LPAREN] = ACTIONS(9),
    [anon_sym_ATeach_LPAREN] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(43),
    [sym_brace_statement] = STATE(43),
    [sym_statement] = STATE(54),
    [sym_expression_statement] = STATE(59),
    [sym_assign_statement] = STATE(59),
    [sym_block_statement] = STATE(59),
    [sym_component_statement] = STATE(43),
    [sym_dump_statement] = STATE(43),
    [sym_each_statement] = STATE(43),
    [sym_string_literal] = STATE(59),
    [sym__expression] = STATE(38),
    [sym_prefix_expression] = STATE(38),
    [sym_prefix_minus] = STATE(33),
    [sym_prefix_not] = STATE(33),
    [sym_infix_expression] = STATE(38),
    [sym_multiply] = STATE(27),
    [sym_modulo] = STATE(27),
    [sym_divide] = STATE(27),
    [sym_minus] = STATE(27),
    [sym_plus] = STATE(27),
    [sym_boolean_literal] = STATE(38),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_ATcomponent_LPAREN] = ACTIONS(7),
    [anon_sym_ATdump_LPAREN] = ACTIONS(9),
    [anon_sym_ATeach_LPAREN] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(21),
    [sym_number_int] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_number_int,
    STATE(49), 1,
      sym_argument_list,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(21), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [37] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(19), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [71] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(24), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [105] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(39), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [139] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(28), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [173] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(29), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [207] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(30), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [241] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(31), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [275] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(61), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(32), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [309] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(41), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [343] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(37), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [377] = 8,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      sym_number_int,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_prefix_minus,
      sym_prefix_not,
    STATE(40), 4,
      sym__expression,
      sym_prefix_expression,
      sym_infix_expression,
      sym_boolean_literal,
    STATE(27), 5,
      sym_multiply,
      sym_modulo,
      sym_divide,
      sym_minus,
      sym_plus,
  [411] = 6,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(80), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(83), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(86), 1,
      anon_sym_ATeach_LPAREN,
    STATE(15), 6,
      sym__definition,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
      aux_sym_program_repeat1,
  [435] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(11), 1,
      anon_sym_ATeach_LPAREN,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(15), 6,
      sym__definition,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
      aux_sym_program_repeat1,
  [459] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(11), 1,
      anon_sym_ATeach_LPAREN,
    STATE(47), 1,
      sym_block_statement,
    STATE(43), 5,
      sym__definition,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [482] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(11), 1,
      anon_sym_ATeach_LPAREN,
    STATE(58), 1,
      sym_block_statement,
    STATE(43), 5,
      sym__definition,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [505] = 1,
    ACTIONS(91), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [516] = 1,
    ACTIONS(93), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
  [527] = 8,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_PLUS,
    STATE(44), 1,
      aux_sym_argument_list_repeat1,
  [552] = 1,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
  [563] = 1,
    ACTIONS(111), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [574] = 1,
    ACTIONS(113), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [585] = 1,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
  [596] = 1,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
  [607] = 1,
    ACTIONS(119), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [618] = 4,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(121), 5,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
  [635] = 1,
    ACTIONS(123), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [646] = 1,
    ACTIONS(125), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [657] = 1,
    ACTIONS(127), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [668] = 4,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(129), 5,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
  [685] = 1,
    ACTIONS(131), 8,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [696] = 1,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
  [707] = 1,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
  [718] = 2,
    ACTIONS(139), 1,
      anon_sym_EQ,
    ACTIONS(137), 6,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_PLUS,
  [730] = 6,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_PLUS,
    ACTIONS(141), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [750] = 6,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_PLUS,
    ACTIONS(143), 1,
      anon_sym_RBRACE_RBRACE,
  [769] = 6,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_PLUS,
    ACTIONS(145), 1,
      anon_sym_RBRACE_RBRACE,
  [788] = 6,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_PLUS,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
  [807] = 6,
    ACTIONS(99), 1,
      anon_sym_DASH,
    ACTIONS(101), 1,
      anon_sym_STAR,
    ACTIONS(103), 1,
      anon_sym_PERCENT,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    ACTIONS(107), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
  [826] = 3,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    STATE(48), 1,
      sym_string_literal,
  [836] = 1,
    ACTIONS(151), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_ATelse,
      anon_sym_ATend,
  [842] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_argument_list_repeat1,
  [852] = 3,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_argument_list_repeat1,
  [862] = 1,
    ACTIONS(158), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [868] = 2,
    ACTIONS(160), 1,
      anon_sym_ATelse,
    ACTIONS(162), 1,
      anon_sym_ATend,
  [875] = 2,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
  [882] = 1,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
  [886] = 1,
    ACTIONS(170), 1,
      sym_identifier,
  [890] = 1,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
  [894] = 1,
    ACTIONS(174), 1,
      anon_sym_SQUOTE,
  [898] = 1,
    ACTIONS(176), 1,
      aux_sym_string_literal_token1,
  [902] = 1,
    ACTIONS(178), 1,
      anon_sym_RBRACE_RBRACE,
  [906] = 1,
    ACTIONS(180), 1,
      aux_sym_string_literal_token2,
  [910] = 1,
    ACTIONS(182), 1,
      anon_sym_in,
  [914] = 1,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
  [918] = 1,
    ACTIONS(184), 1,
      anon_sym_ATend,
  [922] = 1,
    ACTIONS(186), 1,
      anon_sym_RBRACE_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 37,
  [SMALL_STATE(5)] = 71,
  [SMALL_STATE(6)] = 105,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 173,
  [SMALL_STATE(9)] = 207,
  [SMALL_STATE(10)] = 241,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 309,
  [SMALL_STATE(13)] = 343,
  [SMALL_STATE(14)] = 377,
  [SMALL_STATE(15)] = 411,
  [SMALL_STATE(16)] = 435,
  [SMALL_STATE(17)] = 459,
  [SMALL_STATE(18)] = 482,
  [SMALL_STATE(19)] = 505,
  [SMALL_STATE(20)] = 516,
  [SMALL_STATE(21)] = 527,
  [SMALL_STATE(22)] = 552,
  [SMALL_STATE(23)] = 563,
  [SMALL_STATE(24)] = 574,
  [SMALL_STATE(25)] = 585,
  [SMALL_STATE(26)] = 596,
  [SMALL_STATE(27)] = 607,
  [SMALL_STATE(28)] = 618,
  [SMALL_STATE(29)] = 635,
  [SMALL_STATE(30)] = 646,
  [SMALL_STATE(31)] = 657,
  [SMALL_STATE(32)] = 668,
  [SMALL_STATE(33)] = 685,
  [SMALL_STATE(34)] = 696,
  [SMALL_STATE(35)] = 707,
  [SMALL_STATE(36)] = 718,
  [SMALL_STATE(37)] = 730,
  [SMALL_STATE(38)] = 750,
  [SMALL_STATE(39)] = 769,
  [SMALL_STATE(40)] = 788,
  [SMALL_STATE(41)] = 807,
  [SMALL_STATE(42)] = 826,
  [SMALL_STATE(43)] = 836,
  [SMALL_STATE(44)] = 842,
  [SMALL_STATE(45)] = 852,
  [SMALL_STATE(46)] = 862,
  [SMALL_STATE(47)] = 868,
  [SMALL_STATE(48)] = 875,
  [SMALL_STATE(49)] = 882,
  [SMALL_STATE(50)] = 886,
  [SMALL_STATE(51)] = 890,
  [SMALL_STATE(52)] = 894,
  [SMALL_STATE(53)] = 898,
  [SMALL_STATE(54)] = 902,
  [SMALL_STATE(55)] = 906,
  [SMALL_STATE(56)] = 910,
  [SMALL_STATE(57)] = 914,
  [SMALL_STATE(58)] = 918,
  [SMALL_STATE(59)] = 922,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_minus, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_statement, 9, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dump_statement, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_not, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_statement, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_statement, 3, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expression, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_minus, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiply, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modulo, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_divide, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plus, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expression, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_statement, 5, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_statement, 7, 0, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_statement, 3, 0, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [172] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_textwire(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "textwire",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
