/* Automatically generated by tree-sitter v0.25.2 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 44
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  anon_sym_EQ = 2,
  anon_sym_COMMA = 3,
  anon_sym_ATcomponent_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_ATdump_LPAREN = 6,
  anon_sym_ATeach_LPAREN = 7,
  anon_sym_in = 8,
  anon_sym_ATelse = 9,
  anon_sym_ATend = 10,
  sym_identifier = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_string_literal_token1 = 13,
  anon_sym_SQUOTE = 14,
  aux_sym_string_literal_token2 = 15,
  sym_open_braces = 16,
  sym_close_braces = 17,
  sym_number_int = 18,
  sym_program = 19,
  sym_definition = 20,
  sym_brace_statement = 21,
  sym_statement = 22,
  sym_assign_statement = 23,
  sym_block_statement = 24,
  sym_argument_list = 25,
  sym_component_statement = 26,
  sym_dump_statement = 27,
  sym_each_statement = 28,
  sym_string_literal = 29,
  sym_expression = 30,
  aux_sym_program_repeat1 = 31,
  aux_sym_argument_list_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_ATcomponent_LPAREN] = "@component(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATdump_LPAREN] = "@dump(",
  [anon_sym_ATeach_LPAREN] = "@each(",
  [anon_sym_in] = " in ",
  [anon_sym_ATelse] = "@else",
  [anon_sym_ATend] = "@end",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_open_braces] = "open_braces",
  [sym_close_braces] = "close_braces",
  [sym_number_int] = "number_int",
  [sym_program] = "program",
  [sym_definition] = "definition",
  [sym_brace_statement] = "brace_statement",
  [sym_statement] = "statement",
  [sym_assign_statement] = "assign_statement",
  [sym_block_statement] = "block_statement",
  [sym_argument_list] = "argument_list",
  [sym_component_statement] = "component_statement",
  [sym_dump_statement] = "dump_statement",
  [sym_each_statement] = "each_statement",
  [sym_string_literal] = "string_literal",
  [sym_expression] = "expression",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_ATcomponent_LPAREN] = anon_sym_ATcomponent_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATdump_LPAREN] = anon_sym_ATdump_LPAREN,
  [anon_sym_ATeach_LPAREN] = anon_sym_ATeach_LPAREN,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_ATelse] = anon_sym_ATelse,
  [anon_sym_ATend] = anon_sym_ATend,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_open_braces] = sym_open_braces,
  [sym_close_braces] = sym_close_braces,
  [sym_number_int] = sym_number_int,
  [sym_program] = sym_program,
  [sym_definition] = sym_definition,
  [sym_brace_statement] = sym_brace_statement,
  [sym_statement] = sym_statement,
  [sym_assign_statement] = sym_assign_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_argument_list] = sym_argument_list,
  [sym_component_statement] = sym_component_statement,
  [sym_dump_statement] = sym_dump_statement,
  [sym_each_statement] = sym_each_statement,
  [sym_string_literal] = sym_string_literal,
  [sym_expression] = sym_expression,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcomponent_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdump_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATeach_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_open_braces] = {
    .visible = true,
    .named = true,
  },
  [sym_close_braces] = {
    .visible = true,
    .named = true,
  },
  [sym_number_int] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_component_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_dump_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_each_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_array = 2,
  field_name = 3,
  field_value = 4,
  field_var = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_array] = "array",
  [field_name] = "name",
  [field_value] = "value",
  [field_var] = "var",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_value, 2},
  [3] =
    {field_array, 3},
    {field_var, 1},
  [5] =
    {field_alternative, 7},
    {field_array, 3},
    {field_var, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
};

const TSCharacterRange sym_name_character_set_1[] = {
  {'0', '9'}, {'A', 'Z'}, {'_', '_'}, {'a', 'z'}, {0x80, 0x9f}, {0xa1, 0x200a}, {0x200c, 0x205f}, {0x2061, 0xfefe},
  {0xff00, 0xffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '"', 38,
        '\'', 41,
        ')', 32,
        ',', 30,
        '=', 29,
        '@', 8,
        '{', 26,
        '}', 27,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (set_contains(sym_name_character_set_1, 9, lookahead)) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(19);
      if (lookahead == 'd') ADVANCE(25);
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == '{') ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(46);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_ATcomponent_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_ATdump_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_ATeach_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_ATelse);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_name);
      if (set_contains(sym_name_character_set_1, 9, lookahead)) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_open_braces);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_close_braces);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 42},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_ATcomponent_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATdump_LPAREN] = ACTIONS(1),
    [anon_sym_ATeach_LPAREN] = ACTIONS(1),
    [anon_sym_ATelse] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_open_braces] = ACTIONS(1),
    [sym_close_braces] = ACTIONS(1),
    [sym_number_int] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(30),
    [sym_definition] = STATE(4),
    [sym_brace_statement] = STATE(8),
    [sym_component_statement] = STATE(8),
    [sym_dump_statement] = STATE(8),
    [sym_each_statement] = STATE(8),
    [aux_sym_program_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_ATcomponent_LPAREN] = ACTIONS(5),
    [anon_sym_ATdump_LPAREN] = ACTIONS(7),
    [anon_sym_ATeach_LPAREN] = ACTIONS(9),
    [sym_open_braces] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(7), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATeach_LPAREN,
    ACTIONS(11), 1,
      sym_open_braces,
    ACTIONS(13), 1,
      sym_identifier,
    STATE(15), 1,
      sym_definition,
    STATE(38), 1,
      sym_statement,
    STATE(40), 2,
      sym_assign_statement,
      sym_block_statement,
    STATE(8), 4,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [32] = 7,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(20), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(23), 1,
      anon_sym_ATeach_LPAREN,
    ACTIONS(26), 1,
      sym_open_braces,
    STATE(3), 2,
      sym_definition,
      aux_sym_program_repeat1,
    STATE(8), 4,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [58] = 7,
    ACTIONS(5), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(7), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATeach_LPAREN,
    ACTIONS(11), 1,
      sym_open_braces,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_definition,
      aux_sym_program_repeat1,
    STATE(8), 4,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [84] = 7,
    ACTIONS(5), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(7), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATeach_LPAREN,
    ACTIONS(11), 1,
      sym_open_braces,
    STATE(15), 1,
      sym_definition,
    STATE(21), 1,
      sym_block_statement,
    STATE(8), 4,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [109] = 7,
    ACTIONS(5), 1,
      anon_sym_ATcomponent_LPAREN,
    ACTIONS(7), 1,
      anon_sym_ATdump_LPAREN,
    ACTIONS(9), 1,
      anon_sym_ATeach_LPAREN,
    ACTIONS(11), 1,
      sym_open_braces,
    STATE(15), 1,
      sym_definition,
    STATE(42), 1,
      sym_block_statement,
    STATE(8), 4,
      sym_brace_statement,
      sym_component_statement,
      sym_dump_statement,
      sym_each_statement,
  [134] = 1,
    ACTIONS(31), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [145] = 1,
    ACTIONS(33), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [156] = 1,
    ACTIONS(35), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [167] = 1,
    ACTIONS(37), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [178] = 1,
    ACTIONS(39), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [189] = 1,
    ACTIONS(41), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [200] = 1,
    ACTIONS(43), 8,
      ts_builtin_sym_end,
      anon_sym_ATcomponent_LPAREN,
      anon_sym_ATdump_LPAREN,
      anon_sym_ATeach_LPAREN,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_open_braces,
      sym_close_braces,
  [211] = 3,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      aux_sym_argument_list_repeat1,
  [221] = 1,
    ACTIONS(49), 3,
      anon_sym_ATelse,
      anon_sym_ATend,
      sym_close_braces,
  [227] = 1,
    ACTIONS(51), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_close_braces,
  [233] = 3,
    ACTIONS(45), 1,
      anon_sym_COMMA,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
  [243] = 3,
    ACTIONS(55), 1,
      sym_number_int,
    STATE(14), 1,
      sym_expression,
    STATE(29), 1,
      sym_argument_list,
  [253] = 3,
    ACTIONS(57), 1,
      anon_sym_COMMA,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      aux_sym_argument_list_repeat1,
  [263] = 3,
    ACTIONS(62), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_SQUOTE,
    STATE(28), 1,
      sym_string_literal,
  [273] = 2,
    ACTIONS(66), 1,
      anon_sym_ATelse,
    ACTIONS(68), 1,
      anon_sym_ATend,
  [280] = 2,
    ACTIONS(55), 1,
      sym_number_int,
    STATE(36), 1,
      sym_expression,
  [287] = 2,
    ACTIONS(55), 1,
      sym_number_int,
    STATE(34), 1,
      sym_expression,
  [294] = 2,
    ACTIONS(55), 1,
      sym_number_int,
    STATE(27), 1,
      sym_expression,
  [301] = 2,
    ACTIONS(55), 1,
      sym_number_int,
    STATE(37), 1,
      sym_expression,
  [308] = 1,
    ACTIONS(70), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [313] = 1,
    ACTIONS(60), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [318] = 2,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
  [325] = 1,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
  [329] = 1,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
  [333] = 1,
    ACTIONS(80), 1,
      aux_sym_string_literal_token1,
  [337] = 1,
    ACTIONS(82), 1,
      anon_sym_SQUOTE,
  [341] = 1,
    ACTIONS(84), 1,
      anon_sym_in,
  [345] = 1,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
  [349] = 1,
    ACTIONS(88), 1,
      anon_sym_EQ,
  [353] = 1,
    ACTIONS(90), 1,
      sym_close_braces,
  [357] = 1,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
  [361] = 1,
    ACTIONS(94), 1,
      sym_close_braces,
  [365] = 1,
    ACTIONS(96), 1,
      sym_identifier,
  [369] = 1,
    ACTIONS(98), 1,
      sym_close_braces,
  [373] = 1,
    ACTIONS(100), 1,
      aux_sym_string_literal_token2,
  [377] = 1,
    ACTIONS(102), 1,
      anon_sym_ATend,
  [381] = 1,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 109,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 145,
  [SMALL_STATE(9)] = 156,
  [SMALL_STATE(10)] = 167,
  [SMALL_STATE(11)] = 178,
  [SMALL_STATE(12)] = 189,
  [SMALL_STATE(13)] = 200,
  [SMALL_STATE(14)] = 211,
  [SMALL_STATE(15)] = 221,
  [SMALL_STATE(16)] = 227,
  [SMALL_STATE(17)] = 233,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 253,
  [SMALL_STATE(20)] = 263,
  [SMALL_STATE(21)] = 273,
  [SMALL_STATE(22)] = 280,
  [SMALL_STATE(23)] = 287,
  [SMALL_STATE(24)] = 294,
  [SMALL_STATE(25)] = 301,
  [SMALL_STATE(26)] = 308,
  [SMALL_STATE(27)] = 313,
  [SMALL_STATE(28)] = 318,
  [SMALL_STATE(29)] = 325,
  [SMALL_STATE(30)] = 329,
  [SMALL_STATE(31)] = 333,
  [SMALL_STATE(32)] = 337,
  [SMALL_STATE(33)] = 341,
  [SMALL_STATE(34)] = 345,
  [SMALL_STATE(35)] = 349,
  [SMALL_STATE(36)] = 353,
  [SMALL_STATE(37)] = 357,
  [SMALL_STATE(38)] = 361,
  [SMALL_STATE(39)] = 365,
  [SMALL_STATE(40)] = 369,
  [SMALL_STATE(41)] = 373,
  [SMALL_STATE(42)] = 377,
  [SMALL_STATE(43)] = 381,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_statement, 5, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_statement, 3, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dump_statement, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_statement, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_statement, 7, 0, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_statement, 9, 0, 4),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [78] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_statement, 3, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_textwire(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
    .name = "textwire",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
